version: '3'

volumes:
  prometheus-data:

networks:
  prometheus-network:

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
            - prometheus-network
    env_file:
            - .env
    command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/etc/prometheus/console_libraries'
            - '--web.console.templates=/etc/prometheus/consoles'
            - '--storage.tsdb.retention=220h'
            - '--web.enable-lifecycle'
    restart: always
    ports:
            - '9090:9090'

  pushgateway:
    container_name: pushgateway
    image: prom/pushgateway
    ports:
          - 9091:9091
    networks:
          - prometheus-network
